name: practice-test
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  MY_NAME: Neerukonda Murali Krishna
jobs:
  print-myname:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "My Name is $MY_NAME"
  print-my-role:
    runs-on: ubuntu-latest
    env:
      MY_ROLE: Software Engineer
    steps:
      - name: print role
        run: echo "My Role is $MY_ROLE"
